import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import grid from '../css.module/grid.module.css'
import urlHome from "../package.json";
import Link from 'next/link'
import projectList from "../data/projectList";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>UnityOnNext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className={styles.center} >
          {/* <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          /> */}
          <img
            className={styles.logo}
            src={`${urlHome.homepage}/next.svg`}
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            {/* <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            /> */}
            <img
              src={`${urlHome.homepage}/thirteen.svg`}
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
        <div className={styles.center}>
          <div className={grid.container}>
            {projectList.map(
              project => <div key={project.image} className={grid.element}>
                <Link href={project.link}>
                  <div style={{ paddingBottom: 30, paddingTop: 30 }}>
                    <img style={{ width: "100%" }} src={project.image} alt={project.title} />
                    <div>
                      <h4 className={grid.element__name}>{project.title}</h4>
                      <h5 className={grid.element__name}>{project.description}</h5>
                    </div>
                  </div>
                </Link>
              </div>
            )}
          </div>
        </div>
      </main>
    </>
  )
}
