import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import urlHome from "../package.json";
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>UnityOnNext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          {/* <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          /> */}
          <img
            className={styles.logo}
            src={`${urlHome.homepage}/next.svg`}
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            {/* <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            /> */}
            <img
              src={`${urlHome.homepage}/thirteen.svg`}
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
        <div style={{ display: "flex", flexWrap: "wrap", marginLeft: 75 }}>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/runner">Runner</Link>
            </li>
            <li>
              <Link href="/robocop">Robocop</Link>
            </li>
            <li>
              <Link href="/runner2">Runner2</Link>
            </li>
            <li>
              <Link href="/pacman">Pacman</Link>
            </li>
            <li>
              <Link href="/garden">Garden</Link>
            </li>
            <li>
              <Link href="/movements">Camera controll abd Movement</Link>
            </li>
          </ul>
        </div>
      </main>
    </>
  )
}
