import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Unity, useUnityContext } from "react-unity-webgl";
import urlHome from "../package.json";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { unityProvider } = new useUnityContext({
    dataUrl: `${urlHome.homepage}build/ReactBuild.data`,
    frameworkUrl: `${urlHome.homepage}build/ReactBuild.framework.js`,
    loaderUrl: `${urlHome.homepage}build/ReactBuild.loader.js`,
    codeUrl: `${urlHome.homepage}build/ReactBuild.wasm`,
  });
  return (
    <>
      <Head>
        <title>UnityOnNext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          {/* <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          /> */}
          <img
            className={styles.logo}
            src={`${urlHome.homepage}/next.svg`}
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            {/* <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            /> */}
            <img
              src={`${urlHome.homepage}/thirteen.svg`}
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
        <Unity unityProvider={unityProvider} style={{ width: 800, height: 600, border: "solid black 1px" }} />
      </main>
    </>
  )
}
